config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  
  root 'users#index'

  resources :interests
  
  resources :users, only: [:index, :show]

  resources :users do
    member do
      put "follow", to: "users#followed"
      put "unfollow", to: "users#unfollowed"
      put "turnoffbd", to: "users#offbd"
      put "turnonbd", to: "users#onbd"
      put "connect", to: "users#connect"
      put "disconnect", to: "users#disconnect"
    end
  end

  resources :interests do
    member do
      put "follow", to: "interests#followed"
      put "unfollow", to: "interests#unfollowed"
    end
  end

end

app/views/main/_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		-# to put the logo and toggle icon
		.navbar-header
			%button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.navbar-brand{:href => "/"} Datezilla
		-# to put the rest of the stuff on the navbar section
		#bs-example-navbar-collapse-1.collapse.navbar-collapse
			-#%ul.nav.navbar-nav
				
			-#search form
			%form.navbar-form.navbar-left{:role => "search"}
				.form-group
					%input.form-control{:type => "text", :id =>"search", :name=>"search", :placeholder=>"Search users by interest", :size=>"30%"}
				%button.btn.btn-default{:type => "submit"} Test my luck!
			-# right hand side of the navigation bar
			%ul.nav.navbar-nav.navbar-right
				- if user_signed_in?
					%li
						= link_to "<i class=\"fa fa-plus fa-fw fa-lg\" style=\"\"></i>Add Interest".html_safe, new_interest_path(:uploadtype=>"normal"), :remote => true, "data-toggle" => "modal", "data-target" => ".bs-listitem-modal-sm"	

					-# modal for post new p interests
					.modal.fade.bs-listitem-modal-sm{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1", :id => "postmodal"}
						.modal-dialog.modal-sm
							.modal-content{:style => "padding: 5px 5px 5px 5px;"}
								.modal-header
									%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
										%span{"aria-hidden" => "true"} &times;
									%h4.modal-title Post a new item
								.modal-body.a-unique-class

				-#Facebook login options
				%li.dropdown{:role => "group",'data-placement'=> 'bottom'}		
					- if user_signed_in?
						%a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button", :href=>"#"}
							- if current_user.provider.present?
								= image_tag(current_user.avatar.url, :class=> "img-circle", :style=>"padding-right:2px; width:25px;height:22px")
							- else
								= image_tag(current_user.gravatar_url, :class=> "img-circle", :style=>"padding-right:2px; width:25px;height:22px")
							
							= current_user.username
							%span.caret	
						%ul.dropdown-menu.dropdown-menu-right{:role => "menu", :style=>"border-radius: 4px"}	
							%li
								= link_to "Log out", destroy_user_session_path, method: :delete
			
					- else
						%li
							= link_to "<i class=\"fa fa-facebook\" style=\"padding-right:5px\"></i>Log in with Facebook".html_safe, user_omniauth_authorize_path(:facebook)		
				

				